# Generated by Django 4.2.7 on 2024-04-15 11:58

from django.db import migrations, models
import django.db.models.deletion
# import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=60, null=True, verbose_name='Статус')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('duration', models.CharField(blank=True, max_length=60, verbose_name='Продолжительность')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Стоимость бани')),
                ('appointment_full_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стоимость заказа рублей')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество')),
                ('source', models.CharField(blank=True, max_length=60, null=True, verbose_name='Источник')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Полное имя')),
                ('comment', models.CharField(blank=True, max_length=60, null=True, verbose_name='Комментарий')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
                ('people_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во чел.')),
                ('prepayment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Предоплата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=60)),
                # ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('phone', models.PositiveSmallIntegerField(blank=True, max_length=128, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('measurement_unit', models.CharField(max_length=200, null=True, verbose_name='Ед изм')),
                ('amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол')),
                ('price', models.PositiveSmallIntegerField(default=100, verbose_name='Цена')),
                ('full_price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Доп Услуга',
                'verbose_name_plural': 'Доп Услуги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointment', to='bath.appointment', verbose_name='Запись бронь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_service', to='bath.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Доп услуга',
                'verbose_name_plural': 'Доп услуги',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bath.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='bath.service', verbose_name='Услуги'),
        ),
    ]
