# Generated by Django 4.2.7 on 2024-04-15 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=2, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Количество'),
        ),
    ]
