# Generated by Django 4.2.7 on 2024-04-15 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0002_alter_appointment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotenburo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ротэнбуро')),
                ('birch_broom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник бер.')),
                ('oak_broom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник дуб')),
                ('bed_sheet', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Простыня')),
                ('towel', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полотенце')),
                ('robe', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Халат')),
                ('slippers', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тапки')),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bath.order', verbose_name='Заказ услуги')),
            ],
        ),
    ]
