# Generated by Django 4.2.7 on 2024-04-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0004_alter_item_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='appointments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bath.appointment', verbose_name='Заказ услуги'),
        ),
    ]
