# Generated by Django 4.2.7 on 2024-04-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0005_alter_item_appointments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Доп. услуга', 'verbose_name_plural': 'Доп. услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Аксессуары'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bath.appointment', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='item',
            name='appointments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bath.appointment', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bed_sheet',
            field=models.PositiveSmallIntegerField(blank=True, help_text='штук', null=True, verbose_name='Простыня'),
        ),
        migrations.AlterField(
            model_name='item',
            name='birch_broom',
            field=models.PositiveSmallIntegerField(blank=True, help_text='штук', null=True, verbose_name='Веник бер.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='oak_broom',
            field=models.PositiveSmallIntegerField(blank=True, help_text='штук', null=True, verbose_name='Веник дуб'),
        ),
        migrations.AlterField(
            model_name='item',
            name='robe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='штук', null=True, verbose_name='Халат'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rotenburo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Количество часов', null=True, verbose_name='Ротэнбуро'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slippers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='штук', null=True, verbose_name='Тапки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='towel',
            field=models.PositiveSmallIntegerField(blank=True, help_text='штук', null=True, verbose_name='Полотенце'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
