# Generated by Django 4.2.7 on 2024-04-16 11:51

from django.db import migrations, models
# import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0008_alter_appointment_options_alter_appointment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, max_length=128,
                                                   null=True,
                                                   # region=None,
                                                   verbose_name='Телефон'),
        ),
    ]
