# Generated by Django 4.2.7 on 2024-04-16 13:12

from django.db import migrations, models



# import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0009_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveSmallIntegerField(max_length=128,
                                                   # region=None,
                           verbose_name='Телефон'),
        ),
    ]
