# Generated by Django 4.2 on 2024-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0010_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveSmallIntegerField(verbose_name='Телефон'),
        ),
    ]
