# Generated by Django 4.2 on 2024-05-07 16:57

import bath.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveSmallIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bed_sheet',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Простыня'),
        ),
        migrations.AlterField(
            model_name='item',
            name='birch_broom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник берёза'),
        ),
        migrations.AlterField(
            model_name='item',
            name='oak_broom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник дуб'),
        ),
        migrations.AlterField(
            model_name='item',
            name='robe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Халат'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rotenburo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ротэнбуро'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slippers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тапки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='towel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полотенце'),
        ),
    ]
