# Generated by Django 4.2 on 2024-05-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0015_remove_item_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bath.item', verbose_name='Аксессуары'),
        ),
    ]
