# Generated by Django 4.2 on 2024-05-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0017_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.ForeignKey(error_messages='Не заполнено поле name', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bath.customer', verbose_name='Гость'),
        ),
    ]
