# Generated by Django 4.2 on 2024-05-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0019_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Аксессуары', 'verbose_name_plural': 'Аксессуар'},
        ),
    ]
