# Generated by Django 4.2 on 2024-05-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0021_alter_product_index_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Аксессуар', 'verbose_name_plural': 'Аксессуары'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
