# Generated by Django 4.2 on 2024-05-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0023_appointmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentitem',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='bath.appointment', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='appointmentitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество'),
        ),
    ]
