# Generated by Django 4.2 on 2024-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0024_alter_appointmentitem_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='количество'),
        ),
    ]
