# Generated by Django 4.2 on 2024-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0025_alter_appointmentitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentitem',
            name='price',
            field=models.CharField(max_length=50, verbose_name='цена'),
        ),
    ]
