# Generated by Django 4.2 on 2024-05-28 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0026_alter_appointmentitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='appointmentitem',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bath.appointment', verbose_name='Заказ'),
        ),
    ]
