# Generated by Django 4.2 on 2024-05-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0027_alter_appointment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='items_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена услуг'),
        ),
    ]
