# Generated by Django 4.2 on 2024-05-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0028_appointment_items_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_full_price',
            new_name='full_price',
        ),
    ]
