# Generated by Django 4.2 on 2024-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0029_rename_appointment_full_price_appointment_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='full_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='items_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена доп.услуг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Цена'),
        ),
    ]
