# Generated by Django 4.2 on 2024-06-01 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0031_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentitem',
            name='times',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Количество часов'),
        ),
    ]
