# Generated by Django 4.2 on 2024-06-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0032_appointmentitem_times_alter_appointment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentitem',
            name='times',
        ),
    ]
