# Generated by Django 4.2 on 2024-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0033_remove_appointmentitem_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentitem',
            name='total_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
