# Generated by Django 4.2 on 2024-06-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0035_alter_appointmentitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentitem',
            name='total_price',
        ),
    ]
