# Generated by Django 4.2 on 2024-06-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0037_appointmentitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='items_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена доп.услуг'),
        ),
    ]
