# Generated by Django 4.2 on 2024-06-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0038_alter_appointment_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='full_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость заказа'),
        ),
    ]
