# Generated by Django 4.2 on 2024-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0039_alter_appointment_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='items_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доп.услуг'),
        ),
    ]
