# Generated by Django 4.2 on 2024-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0040_alter_appointment_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена услуг'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_price',
            field=models.PositiveIntegerField(null=True, verbose_name='Стоимость заказа'),
        ),
    ]
