# Generated by Django 4.2 on 2024-06-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0041_appointment_services_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='full_price',
            field=models.PositiveIntegerField(verbose_name='Стоимость заказа'),
        ),
    ]
