# Generated by Django 4.2 on 2024-06-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0043_remove_appointment_items_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotenburo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=16, verbose_name='Начало')),
                ('end_time', models.CharField(max_length=16, verbose_name='Конец')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotenburos', to='bath.appointment', verbose_name='Заказ')),
            ],
        ),
    ]
