# Generated by Django 4.2 on 2024-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0045_alter_rotenburo_options_alter_rotenburo_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotenburo',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
